clear

INPUT_LENGTH = 16;
resultEncrypt = '';
resultDecrypt = '';
% text -> hex -> Cipher
text = ['Lorem ipsum dolor sit amet, consectetur adipiscing elit. ' ...
    'Proin id lacus eget erat pretium luctus. Duis iaculis, sem eget dictum scelerisque, ' ...
    'dui leo accumsan lorem, laoreet tristique augue ipsum vitae ante. Vivamus ultricies dui ' ...
    'ac justo pretium sollicitudin. Etiam venenatis nec risus nec imperdiet. Cras lacinia tincidunt ' ...
    'lectus sit amet ultrices. Nullam faucibus mi auctor ex sagittis cursus. Suspendisse ' ...
    'ligula nulla, pretium at ligula a, consequat cursus ex. Maecenas ex purus, dignissim ' ...
    'sed consequat et, gravida vel velit. Fusce mollis varius leo quis placerat. Ut eu nisl' ...
    ' vitae justo lobortis tincidunt sed nec turpis. Quisque ullamcorper nisl ut rhoncus ' ...
    'pretium. Aliquam a leo id nisl interdum posuere. Aenean viverra ante turpis, eget ' ...
    'faucibus magna rutrum non. Nullam aliquet diam id diam accumsan, vitae suscipit mi ' ...
    'molestie. Mauris non auctor neque. Nam sapien lacus, lobortis in magna nec, molestie ' ...
    'ullamcorper nibh. Pellentesque cursus urna dui. Maecenas ac ipsum magna. Nulla blandit ' ...
    'ipsum at risus euismod interdum. Integer sit amet tincidunt ante, vel ultricies nibh. ' ...
    'Nulla nec lorem nec turpis sagittis eleifend. Aenean non imperdiet turpis. Class aptent' ...
    ' taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam ' ...
    'consequat consequat tincidunt. Proin non scelerisque magna. Curabitur eleifend faucibus' ...
    ' lorem ac imperdiet. Vestibulum venenatis, nulla quis imperdiet imperdiet, justo nulla' ...
    ' mollis tortor, id sollicitudin lectus nibh in justo. Etiam at ante vel mauris posuere' ...
    ' sollicitudin. Etiam elit est, interdum eget dolor ac, euismod sagittis est. Integer eu' ...
    ' faucibus lacus. Etiam ex orci, ullamcorper eu sapien quis, commodo pulvinar risus. ' ...
    'Etiam volutpat, velit at laoreet imperdiet, purus sem sollicitudin libero, et ullamcorper' ...
    ' neque justo eget odio. Aenean sit amet imperdiet sapien. Cras in sapien leo. In tempor' ...
    ' ipsum sed massa accumsan, vitae maximus odio dignissim. Maecenas nisl massa, vulputate' ...
    ' a sem et, pellentesque fermentum tellus. Donec eu elementum tortor, pretium consequat ' ...
    'tortor. Aenean consequat dapibus diam, eget scelerisque massa accumsan bibendum. Maecenas' ...
    ' suscipit felis leo, ac consequat neque rhoncus sit amet. Sed in luctus ante, id mollis magna.' ...
    ' Vestibulum placerat magna in sapien rutrum pulvinar. Etiam scelerisque, justo quis tempus ' ...
    'feugiat, neque nulla convallis elit, ut placerat mi dolor vel metus. Pellentesque eget magna' ...
    ' orci. Praesent justo enim, rhoncus a velit vitae, commodo mattis est. Donec in risus metus.' ...
    ' Aliquam non lacus dignissim, eleifend sem at, interdum lectus. Aliquam in ante ac velit ' ...
    'semper auctor vitae a lorem. Mauris pretium est vitae erat sollicitudin pulvinar.Ut et euismod' ...
    ' purus. Etiam sapien dui, commodo eget efficitur ac, molestie nec metus. Nulla feugiat lectus' ...
    ' eu eleifend pretium. In ligula velit, sodales in egestas in, tempor vel turpis. Integer' ...
    ' pulvinar egestas quam, tincidunt scelerisque velit ultricies elementum. Nam mauris sapien,' ...
    ' interdum sed maximus pretium, accumsan elementum orci. Quisque ut semper augue. Integer ' ...
    'accumsan erat eu consequat rhoncus. Praesent elementum tortor ac ante elementum sodales. ' ...
    'Vestibulum fringilla convallis arcu ut congue. Morbi laoreet quis tellus eget condimentum.' ...
    ' Cras pulvinar odio id venenatis laoreet.'];

%% Encrypt
hexFullText = dec2hex(text);
for i = 1:floor(size(hexFullText, 1)/INPUT_LENGTH)
    hexText = hexFullText(INPUT_LENGTH*(i-1)+1:INPUT_LENGTH*(i-1)+INPUT_LENGTH, :);    
    tmp = cellstr(hexText);
    input = strcat(tmp{:});        
    output = UseCipher('Encrypt', input);
    resultEncrypt = [resultEncrypt, output];
end

if isempty(i)
    i = 0;
end
if i*INPUT_LENGTH < size(hexFullText, 1)
    hexText = hexFullText(INPUT_LENGTH*i+1:end, :);
    if size(hexText, 1) < 16
        for ii = 1:16-size(hexText, 1)
            hexText(end+1, :) = '20';
        end
    end
    tmp = cellstr(hexText);
    input = strcat(tmp{:});
    output = UseCipher('Encrypt', input);
    resultEncrypt = [resultEncrypt, output];
end

%% Decrypt
for i = 1:floor(size(resultEncrypt, 2)/(INPUT_LENGTH*2))
    input = resultEncrypt(INPUT_LENGTH*2*(i-1)+1:INPUT_LENGTH*2*(i-1)+INPUT_LENGTH*2);    
    output = UseCipher('Decrypt', input);
    orgStr = char(hex2dec(reshape(output,2,[])'))';
    resultDecrypt = [resultDecrypt, orgStr];
end

disp(text)
disp(resultDecrypt)