function TimingButtonPushed(app)

src = app.UIButtonTimingSet;

% Disable buttons and dropdowns
set(findobj(app.UIFigure, 'type', 'uibutton'), 'Enable', 'Off')
set(findobj(app.UIFigure, 'type', 'uidropdown'), 'Enable', 'Off')

% Visualize OK button
app.UIButtonOK.Visible = 'On'; app.UIButtonOK.Enable = 'On';

UIAxes = app.UIAxes;
xLim = UIAxes.XLim; yLim = UIAxes.YLim;

% asStartPos = [xLim(1), yLim(1); xLim(1), yLim(2)];
% asEndPos = [(xLim(1)+xLim(2))*1/3, yLim(1);...
%     (xLim(1)+xLim(2))*1/3, yLim(2)];
% disStartPos = [(xLim(1)+xLim(2))*2/3, yLim(1);...
%     (xLim(1)+xLim(2))*2/3, yLim(2)];
% disEndPos = [xLim(2), yLim(1); xLim(2), yLim(2)];
asStartPos = [app.UIFigure.UserData.EventTime(1), yLim(1); app.UIFigure.UserData.EventTime(1), yLim(2)];
asEndPos = [app.UIFigure.UserData.EventTime(2), yLim(1); app.UIFigure.UserData.EventTime(2), yLim(2)];
disStartPos = [app.UIFigure.UserData.EventTime(3), yLim(1); app.UIFigure.UserData.EventTime(3), yLim(2)];
disEndPos = [app.UIFigure.UserData.EventTime(4), yLim(1); app.UIFigure.UserData.EventTime(4), yLim(2)];

src.UserData.lineAsStart = drawline('Parent', UIAxes,...
     'Position', asStartPos, ...
     'Deletable', 0, ...
     'InteractionsAllowed', 'translate', ...
     'Label', 'Association Start', ...
     'LabelVisible', 'hover', ...
     'Color', [1 0 0], ...
     'LineWidth', 2);

src.UserData.lineAsEnd = drawline('Parent', UIAxes,...
     'Position', asEndPos, ...
     'Deletable', 0, ...
     'InteractionsAllowed', 'translate', ...
     'Label', 'Association End', ...
     'LabelVisible', 'hover', ...
     'Color', [0 1 0], ...
     'LineWidth', 2);

src.UserData.lineDisStart = drawline('Parent', UIAxes,...
     'Position', disStartPos, ...
     'Deletable', 0, ...
     'InteractionsAllowed', 'translate', ...
     'Label', 'Dissociation Start', ...
     'LabelVisible', 'hover', ...
     'Color', [0 0 1], ...
     'LineWidth', 2);

src.UserData.lineDisEnd = drawline('Parent', UIAxes,...
     'Position', disEndPos, ...
     'Deletable', 0, ...
     'InteractionsAllowed', 'translate', ...
     'Label', 'Dissociation End', ...
     'LabelVisible', 'hover', ...
     'Color', [0 1 1], ...
     'LineWidth', 2);
 
addlistener(src.UserData.lineAsStart, 'ROIMoved', @(lineSrc, event)LineMoveEvent(lineSrc, event, src.UserData, xLim));
addlistener(src.UserData.lineAsEnd, 'ROIMoved', @(lineSrc, event)LineMoveEvent(lineSrc, event, src.UserData, xLim));
addlistener(src.UserData.lineDisStart, 'ROIMoved', @(lineSrc, event)LineMoveEvent(lineSrc, event, src.UserData, xLim));
addlistener(src.UserData.lineDisEnd, 'ROIMoved', @(lineSrc, event)LineMoveEvent(lineSrc, event, src.UserData, xLim));

SetDrawingArea(src.UserData, xLim)

function LineMoveEvent(lineSrc, event, UserData, xLim)
    SetDrawingArea(UserData, xLim)
end

function SetDrawingArea(UserData, xLim)
    % drawingArea = [x, y, w, h];
    UserData.lineAsStart.DrawingArea =...
        [xLim(1)+1, 0,...
        UserData.lineAsEnd.Position(1)-xLim(1)-1, 0];
    UserData.lineAsEnd.DrawingArea =...
        [UserData.lineAsStart.Position(1)+1, 0,...
        UserData.lineDisStart.Position(1)-UserData.lineAsStart.Position(1)-1, 0];
    UserData.lineDisStart.DrawingArea =...
        [UserData.lineAsEnd.Position(1)+1, 0,...
        UserData.lineDisEnd.Position(1) - UserData.lineAsEnd.Position(1)-1, 0];
    UserData.lineDisEnd.DrawingArea =...
        [UserData.lineDisStart.Position(1)+1, 0,...
        floor(xLim(2) - UserData.lineDisStart.Position(1)), 0];
end

% set(findobj(app.UIFigure, 'type', 'uibutton'), 'Enable', 'On')
% set(findobj(app.UIFigure, 'type', 'uidropdown'), 'Enable', 'On')

end